require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResortsController do

  # This should return the minimal set of attributes required to create a valid
  # Resort. As you add validations to Resort, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResortsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all resorts as @resorts" do
      resort = Resort.create! valid_attributes
      get :index, {}, valid_session
      assigns(:resorts).should eq([resort])
    end
		
		it 'mock geocoding' do
			mock_geocoding!
			address = Resort(:address)
			address.lat.should eq(1.0)
			address.lng.should eq(2.0)
		end
  end

  describe "GET show" do
    it "assigns the requested resort as @resort" do
      resort = Resort.create! valid_attributes
      get :show, {:id => resort.to_param}, valid_session
      assigns(:resort).should eq(resort)
    end
  end

  describe "GET new" do
    it "assigns a new resort as @resort" do
      get :new, {}, valid_session
      assigns(:resort).should be_a_new(Resort)
    end
  end

  describe "GET edit" do
    it "assigns the requested resort as @resort" do
      resort = Resort.create! valid_attributes
      get :edit, {:id => resort.to_param}, valid_session
      assigns(:resort).should eq(resort)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Resort" do
        expect {
          post :create, {:resort => valid_attributes}, valid_session
        }.to change(Resort, :count).by(1)
      end

      it "assigns a newly created resort as @resort" do
        post :create, {:resort => valid_attributes}, valid_session
        assigns(:resort).should be_a(Resort)
        assigns(:resort).should be_persisted
      end

      it "redirects to the created resort" do
        post :create, {:resort => valid_attributes}, valid_session
        response.should redirect_to(Resort.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resort as @resort" do
        # Trigger the behavior that occurs when invalid params are submitted
        Resort.any_instance.stub(:save).and_return(false)
        post :create, {:resort => {}}, valid_session
        assigns(:resort).should be_a_new(Resort)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Resort.any_instance.stub(:save).and_return(false)
        post :create, {:resort => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested resort" do
        resort = Resort.create! valid_attributes
        # Assuming there are no other resorts in the database, this
        # specifies that the Resort created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Resort.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => resort.to_param, :resort => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested resort as @resort" do
        resort = Resort.create! valid_attributes
        put :update, {:id => resort.to_param, :resort => valid_attributes}, valid_session
        assigns(:resort).should eq(resort)
      end

      it "redirects to the resort" do
        resort = Resort.create! valid_attributes
        put :update, {:id => resort.to_param, :resort => valid_attributes}, valid_session
        response.should redirect_to(resort)
      end
    end

    describe "with invalid params" do
      it "assigns the resort as @resort" do
        resort = Resort.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Resort.any_instance.stub(:save).and_return(false)
        put :update, {:id => resort.to_param, :resort => {}}, valid_session
        assigns(:resort).should eq(resort)
      end

      it "re-renders the 'edit' template" do
        resort = Resort.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Resort.any_instance.stub(:save).and_return(false)
        put :update, {:id => resort.to_param, :resort => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested resort" do
      resort = Resort.create! valid_attributes
      expect {
        delete :destroy, {:id => resort.to_param}, valid_session
      }.to change(Resort, :count).by(-1)
    end

    it "redirects to the resorts list" do
      resort = Resort.create! valid_attributes
      delete :destroy, {:id => resort.to_param}, valid_session
      response.should redirect_to(resorts_url)
    end
  end

end
